# Generated by Django 5.0.4 on 2024-04-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.AddField(
            model_name="user",
            name="firebase_uid",
            field=models.CharField(default="default", max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
